# Generated by Django 3.2.16 on 2024-04-02 19:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BR', 'Brazil'), ('BG', 'Bulgaria'), ('CA', 'Canada'), ('CN', 'China'), ('CO', 'Colombia'), ('HR', 'Croatia'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('EG', 'Egypt'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('GR', 'Greece'), ('HU', 'Hungary'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IT', 'Italy'), ('JP', 'Japan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KR', 'South Korea'), ('KW', 'Kuwait'), ('MY', 'Malaysia'), ('MX', 'Mexico'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NG', 'Nigeria'), ('NO', 'Norway'), ('PK', 'Pakistan'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RO', 'Romania'), ('RU', 'Russia'), ('SA', 'Saudi Arabia'), ('RS', 'Serbia'), ('SG', 'Singapore'), ('ZA', 'South Africa'), ('ES', 'Spain'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('TH', 'Thailand'), ('TR', 'Turkey'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('US', 'United States'), ('VN', 'Vietnam')], max_length=2, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('phone_number', models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79998887766'. Требуется длина номера - 11 цифр.", regex='^\\+?\\d{11}$')], verbose_name='Номер телефона')),
                ('time', models.TimeField(null=True, verbose_name='Время уведомлений')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('days', models.ManyToManyField(to='weather.Days', verbose_name='Дни уведомлений')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('weather_alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatheralarm')),
            ],
        ),
    ]
