# Generated by Django 3.2.16 on 2024-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20240406_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatheralarm',
            name='days',
        ),
        migrations.AddField(
            model_name='weatheralarm',
            name='days',
            field=models.ManyToManyField(null=True, to='weather.Days', verbose_name='Дни уведомлений'),
        ),
    ]
