# Generated by Django 3.2.16 on 2024-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_days_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
