# Generated by Django 3.2.16 on 2024-07-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_alter_days_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatheralarm',
            name='time_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
