# Generated by Django 3.2.16 on 2024-07-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_weatheralarm_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheralarm',
            name='time_zone',
            field=models.CharField(choices=[('Europe/Moscow', 'Европа/Москва'), ('Europe/Saratov', 'Европа/Саратов'), ('Europe/Volgograd', 'Европа/Волгоград')], max_length=100, verbose_name='Часовой пояс'),
        ),
    ]
