# Generated by Django 3.2.16 on 2024-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_alter_weatheralarm_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheralarm',
            name='time_zone',
            field=models.CharField(choices=[('Europe/Astrakhan', 'Астрахань'), ('Europe/Volgograd', 'Волгоград'), ('Europe/Zaporozhye', 'Запорожье'), ('Europe/Kaliningrad', 'Калининград'), ('Europe/Moscow', 'Москва'), ('Europe/Samara', 'Самара'), ('Europe/Saratov', 'Саратов'), ('Europe/Simferopol', 'Симферополь'), ('Europe/Uzhgorod', 'Ужгород'), ('Europe/Ulyanovsk', 'Ульяновск'), ('UTC', 'UTC')], max_length=100, verbose_name='Часовой пояс'),
        ),
    ]
