# Generated by Django 3.2.16 on 2024-10-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_alter_days_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=12),
        ),
    ]
